In [1]:
import os

In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
import matplotlib.pyplot as plt

In [5]:
%matplotlib inline

In [6]:
data=pd.read_csv('Social_Network_Ads.csv')

In [8]:
data

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
5    15728773    Male   27            58000          0
6    15598044  Female   27            84000          0
7    15694829  Female   32           150000          1
8    15600575    Male   25            33000          0
9    15727311  Female   35            65000          0
10   15570769  Female   26            80000          0
11   15606274  Female   26            52000          0
12   15746139    Male   20            86000          0
13   15704987    Male   32            18000          0
14   15628972    Male   18            82000          0
15   15697686    Male   29            80000          0
16   15733883    Male   47            25000          1
17   15617482    Male   45            26000          1
18   15704583    Male   46            28000          1
19   15621083  Female   48            29000          1
20   15649487    Male   45            22000          1
21   15736760  Female   47            49000          1
22   15714658    Male   48            41000          1
23   15599081  Female   45            22000          1
24   15705113    Male   46            23000          1
25   15631159    Male   47            20000          1
26   15792818    Male   49            28000          1
27   15633531  Female   47            30000          1
28   15744529    Male   29            43000          0
29   15669656    Male   31            18000          0
..        ...     ...  ...              ...        ...
370  15611430  Female   60            46000          1
371  15774744    Male   60            83000          1
372  15629885  Female   39            73000          0
373  15708791    Male   59           130000          1
374  15793890  Female   37            80000          0
375  15646091  Female   46            32000          1
376  15596984  Female   46            74000          0
377  15800215  Female   42            53000          0
378  15577806    Male   41            87000          1
379  15749381  Female   58            23000          1
380  15683758    Male   42            64000          0
381  15670615    Male   48            33000          1
382  15715622  Female   44           139000          1
383  15707634    Male   49            28000          1
384  15806901  Female   57            33000          1
385  15775335    Male   56            60000          1
386  15724150  Female   49            39000          1
387  15627220    Male   39            71000          0
388  15672330    Male   47            34000          1
389  15668521  Female   48            35000          1
390  15807837    Male   48            33000          1
391  15592570    Male   47            23000          1
392  15748589  Female   45            45000          1
393  15635893    Male   60            42000          1
394  15757632  Female   39            59000          0
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [9]:
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
User ID            400 non-null int64
Gender             400 non-null object
Age                400 non-null int64
EstimatedSalary    400 non-null int64
Purchased          400 non-null int64
dtypes: int64(4), object(1)
memory usage: 15.7+ KB


In [11]:
X=data.iloc[:,[2,3]].values
X

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [12]:
y=data.iloc[:,4].values
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1,

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [15]:
X_train

array([[    26,  15000],
       [    55, 125000],
       [    41,  72000],
       [    49,  65000],
       [    35,  72000],
       [    37,  53000],
       [    36,  63000],
       [    43, 133000],
       [    49,  74000],
       [    59,  29000],
       [    31,  74000],
       [    53,  34000],
       [    41,  87000],
       [    41,  71000],
       [    28,  87000],
       [    40,  60000],
       [    60,  34000],
       [    39,  61000],
       [    30, 135000],
       [    40,  47000],
       [    32,  18000],
       [    21,  72000],
       [    35,  47000],
       [    26,  84000],
       [    45,  79000],
       [    36, 125000],
       [    37,  77000],
       [    37,  93000],
       [    36, 126000],
       [    35,  97000],
       [    42, 108000],
       [    25,  33000],
       [    35,  88000],
       [    39,  79000],
       [    41,  80000],
       [    38,  80000],
       [    50,  44000],
       [    47,  43000],
       [    21,  88000],
       [    24,  58000],


In [16]:
X_test

array([[    25,  22000],
       [    53,  82000],
       [    42,  65000],
       [    36,  60000],
       [    35,  75000],
       [    24,  84000],
       [    31,  18000],
       [    24,  55000],
       [    37,  80000],
       [    48,  33000],
       [    37,  70000],
       [    38,  50000],
       [    35,  65000],
       [    35,  39000],
       [    49,  28000],
       [    22,  27000],
       [    26,  15000],
       [    23,  82000],
       [    27,  84000],
       [    47,  23000],
       [    31,  66000],
       [    59, 130000],
       [    46,  32000],
       [    46,  59000],
       [    27,  54000],
       [    27,  57000],
       [    19,  21000],
       [    21,  68000],
       [    31,  71000],
       [    57,  60000],
       [    41,  72000],
       [    21,  16000],
       [    22,  18000],
       [    59,  76000],
       [    39,  73000],
       [    37,  33000],
       [    36, 118000],
       [    53,  72000],
       [    37,  62000],
       [    46,  88000],


In [17]:
y_train

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0,

In [18]:
y_test

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0], dtype=int64)

In [19]:
from sklearn.preprocessing import StandardScaler

In [20]:
SC=StandardScaler()

In [21]:
X_train=SC.fit_transform(X_train)

C:\Users\ssn\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [23]:
X_test=SC.transform(X_test)

C:\Users\ssn\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [24]:
X_train

array([[-1.12629205, -1.60987312],
       [ 1.70392464,  1.59222519],
       [ 0.33761313,  0.04939601],
       [ 1.11836256, -0.15437389],
       [-0.24794894,  0.04939601],
       [-0.05276158, -0.5036937 ],
       [-0.15035526, -0.21259386],
       [ 0.53280049,  1.82510507],
       [ 1.11836256,  0.10761597],
       [ 2.09429935, -1.20233334],
       [-0.63832366,  0.10761597],
       [ 1.50873728, -1.05678341],
       [ 0.33761313,  0.48604578],
       [ 0.33761313,  0.02028602],
       [-0.93110469,  0.48604578],
       [ 0.24001945, -0.29992381],
       [ 2.19189303, -1.05678341],
       [ 0.14242578, -0.27081383],
       [-0.73591734,  1.88332504],
       [ 0.24001945, -0.67835361],
       [-0.54072998, -1.52254317],
       [-1.61426045,  0.04939601],
       [-0.24794894, -0.67835361],
       [-1.12629205,  0.39871582],
       [ 0.72798785,  0.2531659 ],
       [-0.15035526,  1.59222519],
       [-0.05276158,  0.19494593],
       [-0.05276158,  0.66070568],
       [-0.15035526,

In [25]:
X_test

array([[-1.22388573, -1.40610323],
       [ 1.50873728,  0.34049585],
       [ 0.43520681, -0.15437389],
       [-0.15035526, -0.29992381],
       [-0.24794894,  0.13672596],
       [-1.32147941,  0.39871582],
       [-0.63832366, -1.52254317],
       [-1.32147941, -0.44547373],
       [-0.05276158,  0.28227588],
       [ 1.02076889, -1.0858934 ],
       [-0.05276158, -0.00882396],
       [ 0.0448321 , -0.59102366],
       [-0.24794894, -0.15437389],
       [-0.24794894, -0.91123349],
       [ 1.11836256, -1.23144332],
       [-1.51666677, -1.2605533 ],
       [-1.12629205, -1.60987312],
       [-1.41907309,  0.34049585],
       [-1.02869837,  0.39871582],
       [ 0.92317521, -1.37699324],
       [-0.63832366, -0.1252639 ],
       [ 2.09429935,  1.73777512],
       [ 0.82558153, -1.11500338],
       [ 0.82558153, -0.3290338 ],
       [-1.02869837, -0.47458372],
       [-1.02869837, -0.38725376],
       [-1.8094478 , -1.43521321],
       [-1.61426045, -0.06704393],
       [-0.63832366,

In [26]:
from sklearn.neighbors import KNeighborsClassifier


In [28]:
classifier=KNeighborsClassifier(n_neighbors=5,p=2, metric='minkowski')
classifier.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [29]:
y_predictor=classifier.predict(X_test)

In [30]:
y_predictor

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0], dtype=int64)

In [31]:
from sklearn.metrics import confusion_matrix

In [32]:
cm=confusion_matrix(y_test,y_predictor)

In [33]:
cm


array([[49,  1],
       [ 4, 26]], dtype=int64)