In [1]:
import os

In [2]:
print(os.listdir())

['.ipynb_checkpoints', '.project', '10. Excel_ IBD_Demo.xlsx', '10. Excel_ SoftDrink_QL_tabulation.xls', '10.2 lab data sets.xlsx', '10.2 Lab exercise.docx', '10.Excel _Marathon- Stem and leaf.xlsx', '10.Excel _TVMedia_ Tabulation.xls', '10.Excel_ Smartphone usage_freq& SL.xlsx', 'Assignment 1.docx', 'B10IMNrmlznEx3.pdf', 'Banking Data.xlsx', 'base ball player data set.xls', 'Blank Package.emx', 'Cell Phone Survey.xlsx', 'Command Editor.lnk', 'Consumer_Complaints.csv', 'corr Subquery.txt', 'Data Base explanation_Ver1.docx', 'Data base.xlsx', 'debug.log', 'DecisionTree Project.ipynb', 'DecisionTree.txt', 'desktop.ini', 'DIALYSIS.PNG', 'DIALYSIS2.PNG', 'Doc_01.docx', 'employees.csv', 'Facebook Survey.xlsx', 'fwd10thbatchpgcba_day1_practise.zip', 'groupStudy.csv', 'HeartRate.xls', 'HousingData.csv', 'KClustering.PNG', 'KNearestNeighbours Project.ipynb', 'KNN.txt', 'LinearRegressionProject.ipynb', 'loanData.csv', 'LR.txt', 'MachineLearning', 'Naive Bayes Project.ipynb', 'NAIVE BAYES.txt', 

In [3]:
import numpy as np
import pandas as pd

In [4]:
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
Pras_data=pd.read_csv('Social_Network_Ads.csv')

In [7]:
Pras_data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [9]:
Pras_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
User ID            400 non-null int64
Gender             400 non-null object
Age                400 non-null int64
EstimatedSalary    400 non-null int64
Purchased          400 non-null int64
dtypes: int64(4), object(1)
memory usage: 15.7+ KB


In [18]:
X=Pras_data.iloc[:,2:3].values

In [12]:
X

array([[19],
       [35],
       [26],
       [27],
       [19],
       [27],
       [27],
       [32],
       [25],
       [35],
       [26],
       [26],
       [20],
       [32],
       [18],
       [29],
       [47],
       [45],
       [46],
       [48],
       [45],
       [47],
       [48],
       [45],
       [46],
       [47],
       [49],
       [47],
       [29],
       [31],
       [31],
       [27],
       [21],
       [28],
       [27],
       [35],
       [33],
       [30],
       [26],
       [27],
       [27],
       [33],
       [35],
       [30],
       [28],
       [23],
       [25],
       [27],
       [30],
       [31],
       [24],
       [18],
       [29],
       [35],
       [27],
       [24],
       [23],
       [28],
       [22],
       [32],
       [27],
       [25],
       [23],
       [32],
       [59],
       [24],
       [24],
       [23],
       [22],
       [31],
       [25],
       [24],
       [20],
       [33],
       [32],
       [34],
       [18],

In [19]:
y=Pras_data.iloc[:,4].values

In [20]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1,

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25)

In [23]:
X_train

array([[41],
       [26],
       [49],
       [35],
       [36],
       [50],
       [35],
       [33],
       [59],
       [29],
       [48],
       [23],
       [41],
       [35],
       [52],
       [37],
       [26],
       [51],
       [47],
       [47],
       [40],
       [23],
       [46],
       [36],
       [28],
       [23],
       [41],
       [30],
       [18],
       [27],
       [45],
       [41],
       [39],
       [18],
       [22],
       [59],
       [48],
       [32],
       [24],
       [35],
       [60],
       [49],
       [52],
       [42],
       [28],
       [32],
       [57],
       [19],
       [30],
       [32],
       [42],
       [27],
       [41],
       [24],
       [48],
       [35],
       [41],
       [29],
       [52],
       [35],
       [27],
       [35],
       [32],
       [58],
       [40],
       [44],
       [46],
       [45],
       [35],
       [54],
       [40],
       [20],
       [37],
       [58],
       [30],
       [31],
       [54],

In [24]:

X_test

array([[27],
       [24],
       [36],
       [24],
       [42],
       [35],
       [42],
       [20],
       [42],
       [38],
       [40],
       [29],
       [48],
       [29],
       [49],
       [26],
       [28],
       [36],
       [33],
       [38],
       [30],
       [22],
       [43],
       [35],
       [48],
       [30],
       [51],
       [39],
       [35],
       [58],
       [30],
       [28],
       [51],
       [38],
       [58],
       [46],
       [35],
       [46],
       [48],
       [30],
       [29],
       [37],
       [41],
       [27],
       [41],
       [49],
       [59],
       [42],
       [20],
       [25],
       [46],
       [60],
       [55],
       [57],
       [35],
       [39],
       [39],
       [36],
       [38],
       [38],
       [31],
       [55],
       [31],
       [26],
       [49],
       [35],
       [35],
       [47],
       [26],
       [60],
       [45],
       [33],
       [53],
       [36],
       [28],
       [43],
       [46],

In [25]:

y_train

array([0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1], d

In [26]:
y_test

array([1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0], dtype=int64)

In [27]:
from sklearn.preprocessing import StandardScaler

In [28]:
Sc=StandardScaler()

In [29]:
X_train=Sc.fit_transform(X_train)
X_test=Sc.transform(X_test)

C:\Users\ssn\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [30]:
X_train

array([[ 0.36648434],
       [-1.06633887],
       [ 1.13065672],
       [-0.20664495],
       [-0.1111234 ],
       [ 1.22617826],
       [-0.20664495],
       [-0.39768804],
       [ 2.08587219],
       [-0.77977423],
       [ 1.03513517],
       [-1.35290352],
       [ 0.36648434],
       [-0.20664495],
       [ 1.41722136],
       [-0.01560185],
       [-1.06633887],
       [ 1.32169981],
       [ 0.93961362],
       [ 0.93961362],
       [ 0.27096279],
       [-1.35290352],
       [ 0.84409207],
       [-0.1111234 ],
       [-0.87529578],
       [-1.35290352],
       [ 0.36648434],
       [-0.68425268],
       [-1.83051125],
       [-0.97081733],
       [ 0.74857053],
       [ 0.36648434],
       [ 0.17544124],
       [-1.83051125],
       [-1.44842506],
       [ 2.08587219],
       [ 1.03513517],
       [-0.49320959],
       [-1.25738197],
       [-0.20664495],
       [ 2.18139374],
       [ 1.13065672],
       [ 1.41722136],
       [ 0.46200588],
       [-0.87529578],
       [-0

In [31]:

X_test

array([[-0.97081733],
       [-1.25738197],
       [-0.1111234 ],
       [-1.25738197],
       [ 0.46200588],
       [-0.20664495],
       [ 0.46200588],
       [-1.63946816],
       [ 0.46200588],
       [ 0.07991969],
       [ 0.27096279],
       [-0.77977423],
       [ 1.03513517],
       [-0.77977423],
       [ 1.13065672],
       [-1.06633887],
       [-0.87529578],
       [-0.1111234 ],
       [-0.39768804],
       [ 0.07991969],
       [-0.68425268],
       [-1.44842506],
       [ 0.55752743],
       [-0.20664495],
       [ 1.03513517],
       [-0.68425268],
       [ 1.32169981],
       [ 0.17544124],
       [-0.20664495],
       [ 1.99035064],
       [-0.68425268],
       [-0.87529578],
       [ 1.32169981],
       [ 0.07991969],
       [ 1.99035064],
       [ 0.84409207],
       [-0.20664495],
       [ 0.84409207],
       [ 1.03513517],
       [-0.68425268],
       [-0.77977423],
       [-0.01560185],
       [ 0.36648434],
       [-0.97081733],
       [ 0.36648434],
       [ 1

In [34]:
from sklearn.naive_bayes import GaussianNB

In [37]:
classifier=GaussianNB()
classifier.fit(X_train,y_train)

GaussianNB(priors=None)

In [38]:
y_predictor=classifier.predict(X_test)

In [39]:
y_predictor

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0], dtype=int64)

In [40]:
from sklearn.metrics import confusion_matrix

In [41]:
falseCalci=confusion_matrix(y_test,y_predictor)

In [44]:
falseCalci

array([[54,  6],
       [10, 30]], dtype=int64)