In [2]:
import os

In [3]:
print(os.listdir())

['.ipynb_checkpoints', '.project', '10. Excel_ IBD_Demo.xlsx', '10. Excel_ SoftDrink_QL_tabulation.xls', '10.2 lab data sets.xlsx', '10.2 Lab exercise.docx', '10.Excel _Marathon- Stem and leaf.xlsx', '10.Excel _TVMedia_ Tabulation.xls', '10.Excel_ Smartphone usage_freq& SL.xlsx', 'Assignment 1.docx', 'B10IMNrmlznEx3.pdf', 'Banking Data.xlsx', 'base ball player data set.xls', 'Blank Package.emx', 'Cell Phone Survey.xlsx', 'Command Editor.lnk', 'Consumer_Complaints.csv', 'Data Base explanation_Ver1.docx', 'Data base.xlsx', 'DecisionTree Project.ipynb', 'DecisionTree.txt', 'desktop.ini', 'Doc_01.docx', 'employees.csv', 'Facebook Survey.xlsx', 'fwd10thbatchpgcba_day1_practise.zip', 'groupStudy.csv', 'HeartRate.xls', 'heps', 'HousingData.csv', 'KNN.txt', 'LinearRegressionProject.ipynb', 'loanData.csv', 'LR.txt', 'MachineLearning', 'NAIVE BAYES.txt', 'New Car Sales.xlsx', 'Non invasive BGM.docx', 'Practice.ipynb', 'prasanna.txt', 'Pras_logistics.emx', 'PROSTHETIC HAND CONTROL VIA BLUETOOTH.d

In [4]:
import numpy as np

In [5]:
import pandas as pd

In [6]:
import matplotlib.pyplot as plt

In [7]:
%matplotlib inline

In [8]:
data=pd.read_csv('Social_Network_Ads.csv')

In [9]:
data

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
5    15728773    Male   27            58000          0
6    15598044  Female   27            84000          0
7    15694829  Female   32           150000          1
8    15600575    Male   25            33000          0
9    15727311  Female   35            65000          0
10   15570769  Female   26            80000          0
11   15606274  Female   26            52000          0
12   15746139    Male   20            86000          0
13   15704987    Male   32            18000          0
14   15628972    Male   18            82000          0
15   15697686    Male   29            80000          0
16   15733883    Male   47            25000          1
17   15617482    Male   45            26000          1
18   15704583    Male   46            28000          1
19   15621083  Female   48            29000          1
20   15649487    Male   45            22000          1
21   15736760  Female   47            49000          1
22   15714658    Male   48            41000          1
23   15599081  Female   45            22000          1
24   15705113    Male   46            23000          1
25   15631159    Male   47            20000          1
26   15792818    Male   49            28000          1
27   15633531  Female   47            30000          1
28   15744529    Male   29            43000          0
29   15669656    Male   31            18000          0
..        ...     ...  ...              ...        ...
370  15611430  Female   60            46000          1
371  15774744    Male   60            83000          1
372  15629885  Female   39            73000          0
373  15708791    Male   59           130000          1
374  15793890  Female   37            80000          0
375  15646091  Female   46            32000          1
376  15596984  Female   46            74000          0
377  15800215  Female   42            53000          0
378  15577806    Male   41            87000          1
379  15749381  Female   58            23000          1
380  15683758    Male   42            64000          0
381  15670615    Male   48            33000          1
382  15715622  Female   44           139000          1
383  15707634    Male   49            28000          1
384  15806901  Female   57            33000          1
385  15775335    Male   56            60000          1
386  15724150  Female   49            39000          1
387  15627220    Male   39            71000          0
388  15672330    Male   47            34000          1
389  15668521  Female   48            35000          1
390  15807837    Male   48            33000          1
391  15592570    Male   47            23000          1
392  15748589  Female   45            45000          1
393  15635893    Male   60            42000          1
394  15757632  Female   39            59000          0
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
User ID            400 non-null int64
Gender             400 non-null object
Age                400 non-null int64
EstimatedSalary    400 non-null int64
Purchased          400 non-null int64
dtypes: int64(4), object(1)
memory usage: 15.7+ KB


In [11]:
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [12]:
data.tail()

User ID  Gender  Age  EstimatedSalary  Purchased
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

In [13]:
data

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
5    15728773    Male   27            58000          0
6    15598044  Female   27            84000          0
7    15694829  Female   32           150000          1
8    15600575    Male   25            33000          0
9    15727311  Female   35            65000          0
10   15570769  Female   26            80000          0
11   15606274  Female   26            52000          0
12   15746139    Male   20            86000          0
13   15704987    Male   32            18000          0
14   15628972    Male   18            82000          0
15   15697686    Male   29            80000          0
16   15733883    Male   47            25000          1
17   15617482    Male   45            26000          1
18   15704583    Male   46            28000          1
19   15621083  Female   48            29000          1
20   15649487    Male   45            22000          1
21   15736760  Female   47            49000          1
22   15714658    Male   48            41000          1
23   15599081  Female   45            22000          1
24   15705113    Male   46            23000          1
25   15631159    Male   47            20000          1
26   15792818    Male   49            28000          1
27   15633531  Female   47            30000          1
28   15744529    Male   29            43000          0
29   15669656    Male   31            18000          0
..        ...     ...  ...              ...        ...
370  15611430  Female   60            46000          1
371  15774744    Male   60            83000          1
372  15629885  Female   39            73000          0
373  15708791    Male   59           130000          1
374  15793890  Female   37            80000          0
375  15646091  Female   46            32000          1
376  15596984  Female   46            74000          0
377  15800215  Female   42            53000          0
378  15577806    Male   41            87000          1
379  15749381  Female   58            23000          1
380  15683758    Male   42            64000          0
381  15670615    Male   48            33000          1
382  15715622  Female   44           139000          1
383  15707634    Male   49            28000          1
384  15806901  Female   57            33000          1
385  15775335    Male   56            60000          1
386  15724150  Female   49            39000          1
387  15627220    Male   39            71000          0
388  15672330    Male   47            34000          1
389  15668521  Female   48            35000          1
390  15807837    Male   48            33000          1
391  15592570    Male   47            23000          1
392  15748589  Female   45            45000          1
393  15635893    Male   60            42000          1
394  15757632  Female   39            59000          0
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [14]:
X=data.iloc[:,[2,3]].values

In [15]:
X

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [16]:
y=data.iloc[:,4].values

In [17]:
y=y.reshape(-1,1)

In [18]:
y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [21]:
X_train

array([[    40, 142000],
       [    45,  32000],
       [    22,  81000],
       [    37,  75000],
       [    35,  53000],
       [    39,  59000],
       [    33,  41000],
       [    47,  25000],
       [    36, 125000],
       [    31,  71000],
       [    42,  70000],
       [    43, 129000],
       [    19,  26000],
       [    37,  77000],
       [    23,  66000],
       [    39,  61000],
       [    37,  62000],
       [    40,  72000],
       [    35,  73000],
       [    19,  19000],
       [    32,  86000],
       [    18,  86000],
       [    30, 116000],
       [    59,  83000],
       [    35,  75000],
       [    35,  38000],
       [    58,  23000],
       [    36,  54000],
       [    41,  71000],
       [    42,  64000],
       [    24,  58000],
       [    23,  48000],
       [    25,  33000],
       [    37,  72000],
       [    47,  20000],
       [    27, 137000],
       [    46,  96000],
       [    47,  47000],
       [    49,  74000],
       [    42,  54000],


In [22]:
X_test

array([[    39, 134000],
       [    26,  15000],
       [    40,  71000],
       [    26,  35000],
       [    35,  25000],
       [    24,  32000],
       [    57,  74000],
       [    32, 150000],
       [    35,  39000],
       [    27,  89000],
       [    25,  87000],
       [    28,  89000],
       [    19,  76000],
       [    48,  29000],
       [    36, 126000],
       [    35,  22000],
       [    55, 130000],
       [    37,  80000],
       [    40,  78000],
       [    47, 105000],
       [    47,  49000],
       [    27,  96000],
       [    23,  63000],
       [    19,  25000],
       [    28,  32000],
       [    42,  75000],
       [    35,  71000],
       [    24,  55000],
       [    37,  78000],
       [    51, 134000],
       [    37,  71000],
       [    41,  72000],
       [    23,  82000],
       [    34, 112000],
       [    28,  44000],
       [    35,  60000],
       [    35,  58000],
       [    45, 131000],
       [    39,  79000],
       [    37, 137000],


In [23]:
y_train

array([[1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
    

In [24]:
y_test

array([[1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0]], dtype=int64)

In [25]:
from sklearn.preprocessing import StandardScaler

In [26]:
SC=StandardScaler()

In [27]:
X_train=SC.fit_transform(X_train)
X_test=SC.transform(X_test)

C:\Users\ssn\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [28]:
X_train

array([[ 0.19152488,  2.14257431],
       [ 0.66297073, -1.11033127],
       [-1.5056802 ,  0.33869031],
       [-0.09134263,  0.1612591 ],
       [-0.27992098, -0.48932202],
       [ 0.09723571, -0.3118908 ],
       [-0.46849932, -0.84418445],
       [ 0.85154908, -1.31733435],
       [-0.18563181,  1.63985254],
       [-0.65707766,  0.04297162],
       [ 0.38010322,  0.01339975],
       [ 0.47439239,  1.75814002],
       [-1.78854772, -1.28776248],
       [-0.09134263,  0.22040284],
       [-1.41139103, -0.10488772],
       [ 0.09723571, -0.25274707],
       [-0.09134263, -0.2231752 ],
       [ 0.19152488,  0.07254349],
       [-0.27992098,  0.10211536],
       [-1.78854772, -1.49476556],
       [-0.56278849,  0.48654966],
       [-1.88283689,  0.48654966],
       [-0.75136683,  1.37370572],
       [ 1.98301913,  0.39783405],
       [-0.27992098,  0.1612591 ],
       [-0.27992098, -0.93290005],
       [ 1.88872996, -1.37647809],
       [-0.18563181, -0.45975015],
       [ 0.28581405,

In [29]:
X_test

array([[ 0.09723571,  1.90599936],
       [-1.12852352, -1.61305304],
       [ 0.19152488,  0.04297162],
       [-1.12852352, -1.02161566],
       [-0.27992098, -1.31733435],
       [-1.31710186, -1.11033127],
       [ 1.79444079,  0.13168723],
       [-0.56278849,  2.37914927],
       [-0.27992098, -0.90332818],
       [-1.03423435,  0.57526526],
       [-1.22281269,  0.51612152],
       [-0.93994518,  0.57526526],
       [-1.78854772,  0.19083097],
       [ 0.94583825, -1.19904687],
       [-0.18563181,  1.66942441],
       [-0.27992098, -1.40604995],
       [ 1.60586245,  1.78771189],
       [-0.09134263,  0.30911844],
       [ 0.19152488,  0.2499747 ],
       [ 0.85154908,  1.04841516],
       [ 0.85154908, -0.60760949],
       [-1.03423435,  0.78226834],
       [-1.41139103, -0.19360333],
       [-1.78854772, -1.31733435],
       [-0.93994518, -1.11033127],
       [ 0.38010322,  0.1612591 ],
       [-0.27992098,  0.04297162],
       [-1.31710186, -0.43017828],
       [-0.09134263,

In [30]:
from sklearn.svm import SVC

In [31]:
classifier =SVC(kernel='linear')
classifier.fit(X_train,y_train)

C:\Users\ssn\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [32]:
classifier =SVC(kernel='linear')
classifier.fit(X_train,y_train.ravel())

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [33]:
y_predictor=classifier.predict(X_test)

In [34]:
y_predictor

array([1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0], dtype=int64)

In [35]:
from sklearn.metrics import confusion_matrix
error_predictions=confusion_matrix(y_test,y_predictor)

In [38]:
error_predictions

array([[49,  3],
       [ 9, 19]], dtype=int64)